name: Sync labels
on:
  # You can run this with every type of event, but it's better to run it only when you actually need it.
  schedule:
    - cron: "0 9 * * *" # Runs every day at 09:00
  workflow_dispatch: # Allows manual triggering

permissions:
  issues: write

jobs:
  labels:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: .github/labels.yml

      # - uses: EndBug/label-sync@v2
        # with:
          # If you want to use a config file, you can put its path or URL here, multiple files are also allowed (more info in the paragraphs below)
          # as URL:
          # config-file: https://raw.githubusercontent.com/jv-kune-kune/demo-repository/refs/heads/main/.github/workflows/labels.yaml
          
      - uses: EndBug/label-sync@v2
        with:
          # If you want to use a source repo, you can put is name here (only the owner/repo format is accepted)
          source-repo: jv-kune-kune/PiglioTech-General

          # If you're using a private source repo or a URL that needs an 'Authorization' header, you'll need to add a custom token for the action to read it
          request-token: ${{ secrets.GITHUB_TOKEN }}

          # If you want to delete any additional label, set this to true
          delete-other-labels: true

          # If you want the action just to show you the preview of the changes, without actually editing the labels, set this to true
          dry-run: false

          # You can change the token used to change the labels, this is the default one
          token: ${{ secrets.GITHUB_TOKEN }}
